import { useEffect,useMemo,useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Bot,ChevronRight,GitBranch,Kanban,Network,Search,Sparkles } from 'lucide-react';
import { Background,Controls,ReactFlow,type Edge,type Node } from '@xyflow/react';

type Item={id:string;key:string;parentId:string|null;title:string;type:string;status:string;actor:string;version:number};
type Context={workItem:Item;context:{provenance:Array<{level:string;id:string;instructions:string;role?:string}>};effectiveInstructions:string;availableActions:Array<{toState:string}>};
const json=async<T,>(url:string):Promise<T>=>{const r=await fetch(url);if(!r.ok)throw new Error(await r.text());return r.json() as Promise<T>};

export function App(){
 const [view,setView]=useState<'hierarchy'|'board'|'workflow'>('hierarchy'); const [selected,setSelected]=useState('story_demo'); const [palette,setPalette]=useState(false);
 const items=useQuery({queryKey:['items'],queryFn:()=>json<Item[]>('/v1/work-items?projectId=proj_demo')});
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(x=>!x)}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);
 return <div className="app"><aside><div className="brand"><Sparkles size={18}/> AIWork</div><button className="search" onClick={()=>setPalette(true)}><Search size={15}/>Search <kbd>Ctrl K</kbd></button><nav><Nav icon={<Network/>} label="Hierarchy" active={view==='hierarchy'} onClick={()=>setView('hierarchy')}/><Nav icon={<Kanban/>} label="Board" active={view==='board'} onClick={()=>setView('board')}/><Nav icon={<GitBranch/>} label="Workflow" active={view==='workflow'} onClick={()=>setView('workflow')}/></nav><div className="project"><span>DEMO</span><b>AIWork Demo</b></div></aside>
 <main><header><div><small>AIWORK / DEMO</small><h1>{view[0]!.toUpperCase()+view.slice(1)}</h1></div><span className="online">● API connected</span></header>{items.isLoading?<p>Loading…</p>:items.error?<p className="error">API unavailable. Start the backend on port 4300.</p>:view==='hierarchy'?<Hierarchy items={items.data??[]} selected={selected} select={setSelected}/>:view==='board'?<Board items={items.data??[]} select={setSelected}/>:<Workflow/>}</main>
 <Inspector id={selected}/>{palette&&<Palette items={items.data??[]} close={()=>setPalette(false)} select={id=>{setSelected(id);setPalette(false)}}/>}</div>
}
function Nav(p:{icon:React.ReactNode;label:string;active:boolean;onClick:()=>void}){return <button className={p.active?'active':''} onClick={p.onClick}>{p.icon}{p.label}</button>}
function Hierarchy({items,selected,select}:{items:Item[];selected:string;select:(id:string)=>void}){const children=(parent:string|null,depth=0):React.ReactNode=>items.filter(i=>i.parentId===parent).map(i=><div key={i.id}><button className={`tree-row ${selected===i.id?'selected':''}`} style={{paddingLeft:12+depth*22}} onClick={()=>select(i.id)}><ChevronRight size={14}/><span className="type">{i.type}</span><b>{i.key}</b><span>{i.title}</span><i className={`state ${i.status}`}>{i.status.replace('_',' ')}</i>{i.actor&&<em><Bot size={12}/>{i.actor}</em>}</button>{children(i.id,depth+1)}</div>);return <section className="panel"><div className="panel-title">Work hierarchy <span>{items.length} items</span></div>{children(null)}</section>}
function Board({items,select}:{items:Item[];select:(id:string)=>void}){return <div className="board">{['ready','in_progress','test','production'].map(s=><section key={s}><h3>{s.replace('_',' ')} <span>{items.filter(i=>i.status===s).length}</span></h3>{items.filter(i=>i.status===s).map(i=><button className="card" key={i.id} onClick={()=>select(i.id)}><small>{i.key} · {i.type}</small><b>{i.title}</b>{i.actor&&<em><Bot size={12}/>{i.actor}</em>}</button>)}</section>)}</div>}
function Inspector({id}:{id:string}){const context=useQuery({queryKey:['context',id],queryFn:()=>json<Context>(`/v1/work-items/${id}/ai?mode=full&max_tokens=2000`)});return <aside className="inspector"><div className="panel-title"><span><Bot size={16}/> AI Inspector</span><button onClick={()=>navigator.clipboard.writeText(`${location.origin}/v1/work-items/${id}/ai`)}>Copy /ai URL</button></div>{context.data&&<><h2>{context.data.workItem.title}</h2><p className="muted">Exact effective context with provenance</p><div className="provenance">{context.data.context.provenance.map((p,n)=><article key={`${p.level}-${p.id}`}><small>{n+1} · {p.level}{p.role&&` · ${p.role}`}</small><p>{p.instructions}</p></article>)}</div><details><summary>Preview assembled prompt</summary><pre>{context.data.effectiveInstructions}</pre></details></>}</aside>}
function Workflow(){const nodes:Node[]=[['state_ready','Ready',0],['state_progress','In Progress',1],['state_test','Test',2],['state_production','Production',3]].map(([id,label,n])=>({id:String(id),position:{x:Number(n)*190,y:130},data:{label},className:'flow-node'}));const edges:Edge[]=[['ready-progress','state_ready','state_progress'],['progress-test','state_progress','state_test'],['test-progress','state_test','state_progress'],['test-prod','state_test','state_production']].map(([id,source,target])=>({id,source,target,animated:true}));return <section className="flow"><ReactFlow nodes={nodes} edges={edges} fitView><Background/><Controls/></ReactFlow></section>}
function Palette({items,close,select}:{items:Item[];close:()=>void;select:(id:string)=>void}){const [q,setQ]=useState('');const found=useMemo(()=>items.filter(i=>`${i.key} ${i.title}`.toLowerCase().includes(q.toLowerCase())),[items,q]);return <div className="overlay" onMouseDown={close}><div className="palette" onMouseDown={e=>e.stopPropagation()}><input autoFocus placeholder="Search work items…" value={q} onChange={e=>setQ(e.target.value)}/>{found.map(i=><button key={i.id} onClick={()=>select(i.id)}><b>{i.key}</b>{i.title}<small>{i.status}</small></button>)}</div></div>}
